In [1]:
import pandas as pd
import numpy as np

In [97]:
path='./analysis_2017.csv'
data=pd.read_csv(path)

In [98]:
#결측값 확인
data.isnull().sum()

선수명         0
팀명          0
승           0
패           0
세           0
홀드          0
블론          0
경기          0
선발          0
이닝          0
삼진/9        0
볼넷/9        0
홈런/9        0
BABIP       0
LOB%        0
ERA         0
RA9-WAR     0
FIP         0
kFIP        0
WAR         0
연봉(2018)    0
연봉(2017)    0
dtype: int64

In [99]:
#변수들 타입 확인
data.dtypes

선수명          object
팀명           object
승             int64
패             int64
세             int64
홀드            int64
블론            int64
경기            int64
선발            int64
이닝          float64
삼진/9        float64
볼넷/9        float64
홈런/9        float64
BABIP       float64
LOB%        float64
ERA         float64
RA9-WAR     float64
FIP         float64
kFIP        float64
WAR         float64
연봉(2018)      int64
연봉(2017)      int64
dtype: object

In [100]:
#normalization
for d in data.columns:
    if d=='연봉(2018)':
        continue
    if data[d].dtypes=='int64' or data[d].dtypes=='float64':
        mean=data[d].mean()
        std=data[d].std()
        data[d]=data[d].apply(lambda x:(x-mean)/std)

In [101]:
data=data.rename(columns={'연봉(2018)':'y'})

In [102]:
onehot=pd.get_dummies(data['팀명'])

In [103]:
data.join(onehot)

,선수명,팀명,승,패,세,홀드,블론,경기,선발,이닝,...,연봉(2017),KIA,KT,LG,NC,SK,두산,롯데,삼성,한화
0,켈리,SK,3.313623,1.227145,-0.306452,-0.585705,-0.543592,0.059433,2.452068,2.645175,...,2.734705,0,0,0,0,1,0,0,0,0
1,소사,LG,2.019505,2.504721,-0.098502,-0.585705,-0.543592,0.059433,2.349505,2.547755,...,1.337303,0,0,1,0,0,0,0,0,0
2,양현종,KIA,4.348918,0.907751,-0.306452,-0.585705,-0.543592,0.111056,2.554632,2.706808,...,5.329881,1,0,0,0,0,0,0,0,0
3,차우찬,LG,1.760682,1.227145,-0.306452,-0.585705,-0.543592,-0.043811,2.246942,2.350927,...,3.333592,0,0,1,0,0,0,0,0,0
4,레일리,롯데,2.537153,1.227145,-0.306452,-0.585705,-0.543592,0.059433,2.452068,2.587518,...,2.734705,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,장민재,한화,-0.309907,0.588357,-0.306452,-0.585705,0.680497,0.214300,-0.112010,0.104300,...,-0.335587,0,0,0,0,0,0,0,0,1
148,정용운,KIA,-0.051084,-0.369825,-0.306452,-0.585705,-0.543592,-0.198678,0.503369,0.042667,...,-0.535215,1,0,0,0,0,0,0,0,0
149,노경은,롯데,-0.827554,-0.369825,-0.306452,-0.585705,-0.543592,-1.024633,-0.419699,-0.850019,...,-0.020173,0,0,0,0,0,0,1,0,0
150,김승현,삼성,-0.827554,-0.050431,-0.306452,-0.364245,-0.543592,0.627278,-0.624825,-0.273451,...,-0.543201,0,0,0,0,0,0,0,1,0
151,류희운,KT,0.207740,0.268963,-0.306452,-0.585705,-0.543592,-0.250300,0.811058,0.478075,...,-0.539208,0,1,0,0,0,0,0,0,0

In [104]:
data=data.drop(['선수명'], axis=1)
data=data.drop(['팀명'], axis=1)

In [105]:
data

,승,패,세,홀드,블론,경기,선발,이닝,삼진/9,볼넷/9,홈런/9,BABIP,LOB%,ERA,RA9-WAR,FIP,kFIP,WAR,y,연봉(2017)
0,3.313623,1.227145,-0.306452,-0.585705,-0.543592,0.059433,2.452068,2.645175,0.672099,-0.869000,-0.442382,0.016783,0.446615,-0.587056,3.174630,-0.971030,-1.058125,4.503142,140000,2.734705
1,2.019505,2.504721,-0.098502,-0.585705,-0.543592,0.059433,2.349505,2.547755,0.134531,-0.987502,-0.668521,-0.241686,-0.122764,-0.519855,3.114968,-1.061888,-1.073265,4.094734,120000,1.337303
2,4.348918,0.907751,-0.306452,-0.585705,-0.543592,0.111056,2.554632,2.706808,0.109775,-0.885929,-0.412886,-0.095595,0.308584,-0.625456,2.973948,-0.837415,-0.866361,3.761956,230000,5.329881
3,1.760682,1.227145,-0.306452,-0.585705,-0.543592,-0.043811,2.246942,2.350927,0.350266,-0.945180,-0.186746,-0.477680,0.558765,-0.627856,2.740722,-0.698455,-0.760385,2.998081,100000,3.333592
4,2.537153,1.227145,-0.306452,-0.585705,-0.543592,0.059433,2.452068,2.587518,0.155751,-0.877464,-0.294900,-0.196735,0.481122,-0.539055,2.751570,-0.612941,-0.619085,2.809003,111000,2.734705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,-0.309907,0.588357,-0.306452,-0.585705,0.680497,0.214300,-0.112010,0.104300,-0.968896,-0.373829,0.363854,0.162874,-1.002712,0.411349,-1.229537,0.375810,0.475992,-0.859111,7100,-0.335587
148,-0.051084,-0.369825,-0.306452,-0.585705,-0.543592,-0.198678,0.503369,0.042667,-0.777918,0.603817,-0.147418,-0.871003,-0.269422,-0.030253,-0.361721,0.482702,0.622339,-0.874237,7500,-0.535215
149,-0.827554,-0.369825,-0.306452,-0.585705,-0.543592,-1.024633,-0.419699,-0.850019,-0.756699,0.307561,1.219251,0.466294,-1.356417,1.347354,-1.023431,1.348527,1.389397,-0.964995,10000,-0.020173
150,-0.827554,-0.050431,-0.306452,-0.364245,-0.543592,0.627278,-0.624825,-0.273451,0.205264,1.196330,0.226204,0.005545,0.463869,-0.066253,-0.790205,0.728554,0.713175,-1.033063,4000,-0.543201
151,0.207740,0.268963,-0.306452,-0.585705,-0.543592,-0.250300,0.811058,0.478075,-0.449012,0.722320,0.776804,-0.320351,-0.278049,0.389749,-0.942073,1.118709,1.147168,-1.267520,4000,-0.539208

In [106]:
#train data, test data
y=data['y']
x=data[data.columns.difference(['y'])]

In [107]:
x

,BABIP,ERA,FIP,LOB%,RA9-WAR,WAR,kFIP,경기,볼넷/9,블론,삼진/9,선발,세,승,연봉(2017),이닝,패,홀드,홈런/9
0,0.016783,-0.587056,-0.971030,0.446615,3.174630,4.503142,-1.058125,0.059433,-0.869000,-0.543592,0.672099,2.452068,-0.306452,3.313623,2.734705,2.645175,1.227145,-0.585705,-0.442382
1,-0.241686,-0.519855,-1.061888,-0.122764,3.114968,4.094734,-1.073265,0.059433,-0.987502,-0.543592,0.134531,2.349505,-0.098502,2.019505,1.337303,2.547755,2.504721,-0.585705,-0.668521
2,-0.095595,-0.625456,-0.837415,0.308584,2.973948,3.761956,-0.866361,0.111056,-0.885929,-0.543592,0.109775,2.554632,-0.306452,4.348918,5.329881,2.706808,0.907751,-0.585705,-0.412886
3,-0.477680,-0.627856,-0.698455,0.558765,2.740722,2.998081,-0.760385,-0.043811,-0.945180,-0.543592,0.350266,2.246942,-0.306452,1.760682,3.333592,2.350927,1.227145,-0.585705,-0.186746
4,-0.196735,-0.539055,-0.612941,0.481122,2.751570,2.809003,-0.619085,0.059433,-0.877464,-0.543592,0.155751,2.452068,-0.306452,2.537153,2.734705,2.587518,1.227145,-0.585705,-0.294900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,0.162874,0.411349,0.375810,-1.002712,-1.229537,-0.859111,0.475992,0.214300,-0.373829,0.680497,-0.968896,-0.112010,-0.306452,-0.309907,-0.335587,0.104300,0.588357,-0.585705,0.363854
148,-0.871003,-0.030253,0.482702,-0.269422,-0.361721,-0.874237,0.622339,-0.198678,0.603817,-0.543592,-0.777918,0.503369,-0.306452,-0.051084,-0.535215,0.042667,-0.369825,-0.585705,-0.147418
149,0.466294,1.347354,1.348527,-1.356417,-1.023431,-0.964995,1.389397,-1.024633,0.307561,-0.543592,-0.756699,-0.419699,-0.306452,-0.827554,-0.020173,-0.850019,-0.369825,-0.585705,1.219251
150,0.005545,-0.066253,0.728554,0.463869,-0.790205,-1.033063,0.713175,0.627278,1.196330,-0.543592,0.205264,-0.624825,-0.306452,-0.827554,-0.543201,-0.273451,-0.050431,-0.364245,0.226204
151,-0.320351,0.389749,1.118709,-0.278049,-0.942073,-1.267520,1.147168,-0.250300,0.722320,-0.543592,-0.449012,0.811058,-0.306452,0.207740,-0.539208,0.478075,0.268963,-0.585705,0.776804

In [108]:
y

0      140000
1      120000
2      230000
3      100000
4      111000
        ...
147      7100
148      7500
149     10000
150      4000
151      4000
Name: y, Length: 152, dtype: int64

## Data split

In [121]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [127]:
train_data, test_data, train_label, test_label=train_test_split(x,y, test_size=0.3, random_state=19)

In [128]:
train_data

,BABIP,ERA,FIP,LOB%,RA9-WAR,WAR,kFIP,경기,볼넷/9,블론,삼진/9,선발,세,승,연봉(2017),이닝,패,홀드,홈런/9
114,4.601802,7.188985,7.067251,-2.158722,-0.660033,-0.549023,6.087631,-1.437611,5.847553,-0.543592,3.872747,-0.624825,-0.306452,-0.827554,-0.547193,-1.112457,-1.008613,-0.585705,7.659307
43,0.342679,-0.313454,-0.340367,0.576019,-0.166462,0.048464,-0.437413,0.988633,-0.301881,0.680497,0.523560,-0.624825,0.109447,-0.051084,0.339159,0.000916,-0.689219,-0.142784,0.049225
111,0.500008,0.370549,0.830101,0.067029,-0.529860,-0.541460,0.829243,-0.611655,0.908538,-0.543592,-0.105959,-0.624825,-0.306452,-0.827554,-0.551186,-0.712836,-1.008613,-0.585705,0.472008
20,-0.410253,-0.791057,-1.200848,0.938350,0.972547,0.865281,-1.436608,1.401611,-0.543118,2.516629,1.715404,-0.624825,5.100235,0.725387,4.132107,0.040679,0.268963,-0.585705,-0.442382
47,0.016783,-0.512655,-0.821381,0.515630,-0.372569,-0.095236,-1.017754,0.678900,0.134039,3.128673,1.312228,-0.624825,0.317397,-0.309907,-0.499282,-0.217783,-0.050431,0.078677,-0.422718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,0.095447,-0.260654,-0.490016,0.179179,0.289141,-0.148177,-0.381902,2.072700,-0.830910,-0.543592,-0.601087,-0.624825,-0.306452,0.984211,-0.259728,0.239495,0.268963,1.850362,-0.422718
19,-0.331589,-0.927857,-0.971030,1.844180,1.547475,0.872844,-1.093450,1.659722,-1.093308,2.516629,0.689782,-0.624825,7.387680,-0.568731,2.135819,0.100324,-0.050431,-0.585705,-0.186746
98,-0.084357,0.168948,-0.062447,-0.683515,-0.638337,-0.503644,0.021813,-0.405167,-0.102966,-0.543592,-0.204985,-0.317136,-0.306452,-0.568731,-0.551186,-0.496126,-0.689219,-0.585705,-0.363725
110,-0.016931,0.140148,0.541493,0.187806,-0.372569,-0.541460,0.521410,0.988633,0.134039,1.292541,-0.063520,-0.624825,1.357144,-0.309907,0.179456,-0.376836,0.907751,1.407441,0.668651
93,-3.826542,-1.451060,-0.415191,2.715501,-0.529860,-0.488518,-0.467692,-1.334367,2.038544,-0.543592,0.689782,-0.624825,-0.306452,-0.827554,-0.551186,-1.092575,-1.008613,-0.585705,-1.189625

In [129]:
train_label

114      2900
43      20000
111      3300
20     120000
47       6000
        ...
52      10000
19      70000
98       3400
110     18500
93       2700
Name: y, Length: 106, dtype: int64

## Model train

In [130]:
m=linear_model.LinearRegression()

In [131]:
model=m.fit(train_data, train_label)

In [132]:
pred=model.predict(test_data)

In [134]:
pd.DataFrame({'pred':pred, 'target':test_label})

              pred  target
2    162306.527012  230000
42    10226.467369   19000
100    2742.167924    3100
124    3492.258911    5200
27    23587.832320   18800
7    103799.197243  100000
8     28683.086794   16000
136    5020.611114    3000
142    7930.104425    9000
37    24033.527705   23000
149   10264.572665   10000
23    53084.280166   50000
116    5368.509533    6300
30    21506.706164   11000
138    4995.115114    6500
139    4331.250587    3200
80     8428.472965    3000
14    23142.803591   15500
59     7236.751702   15000
18    14857.849943   11500
112   11485.511293    8000
128    5674.519340    7300
77    10673.422475   14000
64     3921.507789    4500
115    5874.130678    2700
78     4437.033654    3800
144    1239.873588    3600
99     3590.556576    4000
150   -4748.825252    4000
76     7817.368925    5800
24    19352.748375   20000
94     5071.562469    4000
118    2169.138708    4200
109    3977.802978    3500
5     50208.235556   85000
75     5641.196303    4200
6     30803.018495   11500
16    44556.479440   29000
1     80501.614004  120000
117    3610.210073    3200
137   12479.375953   10000
82    -4356.722081    2800
146    3608.676875    7600
72     3717.472775    3100
96    -3263.983981    2900
56     4715.774583    7000

## R2 score

In [135]:
print(model.score(train_data, train_label))
print(model.score(test_data, test_label))

0.9408640941140956
0.879153576992732

In [136]:
x.corr()

,BABIP,ERA,FIP,LOB%,RA9-WAR,WAR,kFIP,경기,볼넷/9,블론,삼진/9,선발,세,승,연봉(2017),이닝,패,홀드,홈런/9
BABIP,1.000000,0.733109,0.251126,-0.505478,-0.187058,-0.082995,0.166910,-0.241608,0.276009,-0.112480,0.457523,-0.098909,-0.089212,-0.171111,-0.088754,-0.191514,-0.133354,-0.104307,0.362614
ERA,0.733109,1.000000,0.648004,-0.720091,-0.335584,-0.261508,0.582057,-0.320177,0.521039,-0.160761,0.256840,-0.157775,-0.150348,-0.271086,-0.203305,-0.285392,-0.188036,-0.155712,0.629912
FIP,0.251126,0.648004,1.000000,-0.288050,-0.366308,-0.391414,0.984924,-0.345351,0.629833,-0.209014,-0.154857,-0.151040,-0.199746,-0.303133,-0.268005,-0.296768,-0.233416,-0.211515,0.831042
LOB%,-0.505478,-0.720091,-0.288050,1.000000,0.286893,0.144191,-0.269536,0.105762,-0.150837,0.100633,-0.071284,0.041819,0.167557,0.131178,0.110424,0.103369,-0.020994,0.048123,-0.274543
RA9-WAR,-0.187058,-0.335584,-0.366308,0.286893,1.000000,0.917299,-0.377679,0.281595,-0.398586,0.008766,0.102963,0.742258,0.167669,0.851350,0.643375,0.853354,0.595989,0.003526,-0.187210
WAR,-0.082995,-0.261508,-0.391414,0.144191,0.917299,1.000000,-0.408283,0.197836,-0.394131,-0.058213,0.151791,0.758846,0.084151,0.821420,0.675794,0.832609,0.625641,-0.038613,-0.205014
kFIP,0.166910,0.582057,0.984924,-0.269536,-0.377679,-0.408283,1.000000,-0.373777,0.605008,-0.237815,-0.317594,-0.142685,-0.225259,-0.314159,-0.282666,-0.302288,-0.238688,-0.237353,0.743623
경기,-0.241608,-0.320177,-0.345351,0.105762,0.281595,0.197836,-0.373777,1.000000,-0.364293,0.630526,0.192487,-0.037443,0.434290,0.397074,0.225357,0.376378,0.343147,0.715527,-0.113545
볼넷/9,0.276009,0.521039,0.629833,-0.150837,-0.398586,-0.394131,0.605008,-0.364293,1.000000,-0.137019,0.109345,-0.312935,-0.131394,-0.404710,-0.332379,-0.451101,-0.386313,-0.146806,0.302251
블론,-0.112480,-0.160761,-0.209014,0.100633,0.008766,-0.058213,-0.237815,0.630526,-0.137019,1.000000,0.188423,-0.264160,0.605229,0.105281,0.146584,0.014176,0.121283,0.490076,-0.064804
삼진/9,0.457523,0.256840,-0.154857,-0.071284,0.102963,0.151791,-0.317594,0.192487,0.109345,0.188423,1.000000,-0.055364,0.170436,0.078377,0.104948,0.037343,0.031755,0.186790,0.216017
선발,-0.098909,-0.157775,-0.151040,0.041819,0.742258,0.758846,-0.142685,-0.037443,-0.312935,-0.264160,-0.055364,1.000000,-0.177069,0.773560,0.488559,0.894018,0.771395,-0.285204,-0.058120
세,-0.089212,-0.150348,-0.199746,0.167557,0.167669,0.084151,-0.225259,0.434290,-0.131394,0.605229,0.170436,-0.177069,1.000000,0.053747,0.262664,0.020278,0.066256,0.112716,-0.073111
승,-0.171111,-0.271086,-0.303133,0.131178,0.851350,0.821420,-0.314159,0.397074,-0.404710,0.105281,0.078377,0.773560,0.053747,1.000000,0.629710,0.906093,0.710749,0.092872,-0.116147
연봉(2017),-0.088754,-0.203305,-0.268005,0.110424,0.643375,0.675794,-0.282666,0.225357,-0.332379,0.146584,0.104948,0.488559,0.262664,0.629710,1.000000,0.586874,0.429227,-0.001213,-0.100896
이닝,-0.191514,-0.285392,-0.296768,0.103369,0.853354,0.832609,-0.302288,0.376378,-0.451101,0.014176,0.037343,0.894018,0.020278,0.906093,0.586874,1.000000,0.829018,0.024631,-0.107063
패,-0.133354,-0.188036,-0.233416,-0.020994,0.595989,0.625641,-0.238688,0.343147,-0.386313,0.121283,0.031755,0.771395,0.066256,0.710749,0.429227,0.829018,1.000000,0.098617,-0.064467
홀드,-0.104307,-0.155712,-0.211515,0.048123,0.003526,-0.038613,-0.237353,0.715527,-0.146806,0.490076,0.186790,-0.285204,0.112716,0.092872,-0.001213,0.024631,0.098617,1.000000,-0.076475
홈런/9,0.362614,0.629912,0.831042,-0.274543,-0.187210,-0.205014,0.743623,-0.113545,0.302251,-0.064804,0.216017,-0.058120,-0.073111,-0.116147,-0.100896,-0.107063,-0.064467,-0.076475,1.000000

In [140]:
new_x=x
new_y=y

In [144]:
new_x=new_x.drop(['RA9-WAR', 'FIP'], axis=1)

In [145]:
new_x.corr()

,BABIP,ERA,LOB%,WAR,kFIP,경기,볼넷/9,블론,삼진/9,선발,세,승,연봉(2017),이닝,패,홀드,홈런/9
BABIP,1.000000,0.733109,-0.505478,-0.082995,0.166910,-0.241608,0.276009,-0.112480,0.457523,-0.098909,-0.089212,-0.171111,-0.088754,-0.191514,-0.133354,-0.104307,0.362614
ERA,0.733109,1.000000,-0.720091,-0.261508,0.582057,-0.320177,0.521039,-0.160761,0.256840,-0.157775,-0.150348,-0.271086,-0.203305,-0.285392,-0.188036,-0.155712,0.629912
LOB%,-0.505478,-0.720091,1.000000,0.144191,-0.269536,0.105762,-0.150837,0.100633,-0.071284,0.041819,0.167557,0.131178,0.110424,0.103369,-0.020994,0.048123,-0.274543
WAR,-0.082995,-0.261508,0.144191,1.000000,-0.408283,0.197836,-0.394131,-0.058213,0.151791,0.758846,0.084151,0.821420,0.675794,0.832609,0.625641,-0.038613,-0.205014
kFIP,0.166910,0.582057,-0.269536,-0.408283,1.000000,-0.373777,0.605008,-0.237815,-0.317594,-0.142685,-0.225259,-0.314159,-0.282666,-0.302288,-0.238688,-0.237353,0.743623
경기,-0.241608,-0.320177,0.105762,0.197836,-0.373777,1.000000,-0.364293,0.630526,0.192487,-0.037443,0.434290,0.397074,0.225357,0.376378,0.343147,0.715527,-0.113545
볼넷/9,0.276009,0.521039,-0.150837,-0.394131,0.605008,-0.364293,1.000000,-0.137019,0.109345,-0.312935,-0.131394,-0.404710,-0.332379,-0.451101,-0.386313,-0.146806,0.302251
블론,-0.112480,-0.160761,0.100633,-0.058213,-0.237815,0.630526,-0.137019,1.000000,0.188423,-0.264160,0.605229,0.105281,0.146584,0.014176,0.121283,0.490076,-0.064804
삼진/9,0.457523,0.256840,-0.071284,0.151791,-0.317594,0.192487,0.109345,0.188423,1.000000,-0.055364,0.170436,0.078377,0.104948,0.037343,0.031755,0.186790,0.216017
선발,-0.098909,-0.157775,0.041819,0.758846,-0.142685,-0.037443,-0.312935,-0.264160,-0.055364,1.000000,-0.177069,0.773560,0.488559,0.894018,0.771395,-0.285204,-0.058120
세,-0.089212,-0.150348,0.167557,0.084151,-0.225259,0.434290,-0.131394,0.605229,0.170436,-0.177069,1.000000,0.053747,0.262664,0.020278,0.066256,0.112716,-0.073111
승,-0.171111,-0.271086,0.131178,0.821420,-0.314159,0.397074,-0.404710,0.105281,0.078377,0.773560,0.053747,1.000000,0.629710,0.906093,0.710749,0.092872,-0.116147
연봉(2017),-0.088754,-0.203305,0.110424,0.675794,-0.282666,0.225357,-0.332379,0.146584,0.104948,0.488559,0.262664,0.629710,1.000000,0.586874,0.429227,-0.001213,-0.100896
이닝,-0.191514,-0.285392,0.103369,0.832609,-0.302288,0.376378,-0.451101,0.014176,0.037343,0.894018,0.020278,0.906093,0.586874,1.000000,0.829018,0.024631,-0.107063
패,-0.133354,-0.188036,-0.020994,0.625641,-0.238688,0.343147,-0.386313,0.121283,0.031755,0.771395,0.066256,0.710749,0.429227,0.829018,1.000000,0.098617,-0.064467
홀드,-0.104307,-0.155712,0.048123,-0.038613,-0.237353,0.715527,-0.146806,0.490076,0.186790,-0.285204,0.112716,0.092872,-0.001213,0.024631,0.098617,1.000000,-0.076475
홈런/9,0.362614,0.629912,-0.274543,-0.205014,0.743623,-0.113545,0.302251,-0.064804,0.216017,-0.058120,-0.073111,-0.116147,-0.100896,-0.107063,-0.064467,-0.076475,1.000000

In [154]:
ntrain_data, ntest_data, ntrain_label, ntest_label=train_test_split(new_x, new_y, test_size=0.3, random_state=19)

In [155]:
nm=linear_model.LinearRegression()

In [156]:
new_model=nm.fit(ntrain_data, ntrain_label)

In [159]:
print(new_model.score(ntrain_data, ntrain_label))
print(new_model.score(ntest_data, ntest_label))

0.938753468101058
0.8835806765361855

In [160]:
new_pred=new_model.predict(ntest_data)

In [162]:
pd.DataFrame({"pred":new_pred, "target":ntest_label})

              pred  target
2    161521.877698  230000
42    11377.229651   19000
100    3256.192936    3100
124    3889.670546    5200
27    21764.877537   18800
7    106808.744279  100000
8     30401.691009   16000
136    4972.358295    3000
142    8076.367388    9000
37    22779.290380   23000
149   10749.861560   10000
23    53335.950231   50000
116    4281.249468    6300
30    20717.741107   11000
138    4509.223216    6500
139    3024.312095    3200
80     5061.836104    3000
14    23394.868636   15500
59     8269.818874   15000
18    15798.409700   11500
112   10646.034995    8000
128    6115.094564    7300
77    11258.595707   14000
64     2318.829122    4500
115    4074.493874    2700
78     4215.728919    3800
144     919.645665    3600
99     3287.040888    4000
150   -4379.069762    4000
76     7334.849140    5800
24    19986.081598   20000
94     7606.857769    4000
118    2537.738656    4200
109    5000.414937    3500
5     53398.026958   85000
75     7050.195875    4200
6     29144.405583   11500
16    41967.106710   29000
1     81453.175306  120000
117    5316.967100    3200
137   13019.335149   10000
82    -4140.485486    2800
146    3899.115196    7600
72     4639.638200    3100
96    -2363.093234    2900
56     5406.316445    7000